name: Darshan Transport Frontend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '22.18.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps --ignore-scripts

    - name: Lint code (fail on warnings)
      run: npx eslint --config eslint.config.js "src/**/*.{ts,tsx,js,jsx}" --max-warnings=0

    - name: Build
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/

  deployment:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: dist/

    - name: Publish artifact for manual deployment
      uses: actions/upload-artifact@v4
      with:
        name: darshan-transport-frontend-dist
        path: dist/

  auto-deploy:
    name: Auto deploy to Windows VPS
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    runs-on: [self-hosted, windows, x64, windows-vps]
    needs: deployment

    steps:
      - name: Checkout repo (for deploy script)
        uses: actions/checkout@v4

      - name: Download build artifact (dist)
        uses: actions/download-artifact@v4
        with:
          name: darshan-transport-frontend-dist
          path: ./artifact

      - name: Deploy to IIS folder (darshantransport-website)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $source = Resolve-Path '.\artifact'
          $target = 'C:\inetpub\wwwroot\darshantransport-website'

          if (-not (Test-Path $source)) { throw "Source '$source' not found (artifact missing)." }
          if (-not (Test-Path (Join-Path $source 'index.html'))) { throw "Artifact folder missing index.html." }

          if (-not (Test-Path $target)) { New-Item -ItemType Directory -Force -Path $target | Out-Null }

          # Preserve existing web.config if present
          $existingWebConfig = Join-Path $target 'web.config'
          $keepWebConfig = Test-Path $existingWebConfig

          # Clear target except web.config
          Get-ChildItem -Path $target -Force | Where-Object { -not ($keepWebConfig -and $_.Name -eq 'web.config') } |
            Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

          # Copy new build
          Copy-Item -Path (Join-Path $source '*') -Destination $target -Recurse -Force

          # Recycle app pool for the site
          try {
            Import-Module WebAdministration -ErrorAction Stop | Out-Null
            $site = Get-Item "IIS:\Sites\darshantransport-website" -ErrorAction Stop
            $pool = $site.applicationPool
            if ($pool) { Restart-WebAppPool -Name $pool -ErrorAction SilentlyContinue }
          } catch {
            Write-Host "IIS recycle skipped: $($_.Exception.Message)"
          }
